//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangNoiDiaNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCard
    {
        public int IdentityCardID { get; set; }
        public string ShipperName { get; set; }
        public string FrontFigure { get; set; }
        public string BackSideFigure { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
