//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangNoiDiaNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagesComment
    {
        public int ImageCommentID { get; set; }
        public int CommentID { get; set; }
        public string Image { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
