//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangNoiDiaNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int OrderDetailID { get; set; }
        public int AccountID { get; set; }
        public int StateID { get; set; }
        public int PaymentID { get; set; }
        public int TrackingOrderID { get; set; }
        public int ShipperID { get; set; }
        public string Details { get; set; }
        public int Quantity { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
