//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangNoiDiaNhat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingOrder
    {
        public int TrackingOrderID { get; set; }
        public int OrganizationID { get; set; }
        public int CustomerID { get; set; }
        public int ShipperID { get; set; }
        public int PaymentID { get; set; }
        public int StateID { get; set; }
        public int ServiceID { get; set; }
        public int ShippingDepartmentID { get; set; }
        public string CoderOrder { get; set; }
        public string ShippingCode { get; set; }
        public string Details { get; set; }
        public int ShippingFee { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
